language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - "pip install . --use-mirrors"
  - "pip install misaka"
  - "pip install python-dateutil"
  - "pip install inflect"
  - "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: py.test
